const TOKEN_KEY = 'caredesk-session';
const $ = (selector, root = document) => root.querySelector(selector);
const uid = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const localDate = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const displayDate = value => value ? new Date(`${value}T12:00:00`).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}) : '—';
const displayTime = value => value ? new Date(`2000-01-01T${value}`).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'}) : '—';
const initials = name => name.split(/\s+/).map(part => part[0]).slice(0,2).join('').toUpperCase();

let db={doctors:[],patients:[],appointments:[]}, view='dashboard', query='', statusFilter='all', toastTimer;
async function request(route,options={}){const token=sessionStorage.getItem(TOKEN_KEY);const response=await fetch(`/api/${route}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const result=await response.json();if(response.status===401&&!['login','signup'].includes(route)){sessionStorage.removeItem(TOKEN_KEY);showLogin();throw new Error('Session expired. Please sign in again.')}if(!response.ok)throw new Error(result.error||'Request failed.');return result}
async function refresh(){const [doctors,patients,appointments]=await Promise.all(['doctors','patients','appointments'].map(route=>request(route)));db={doctors,patients,appointments};render()}
function showLogin(){document.body.classList.add('login-mode');$('#app').innerHTML=`<div class="login-card"><div class="login-logo">✚</div><p class="eyebrow">Practice workspace</p><h1>Sign in to CareDesk</h1><p>Manage appointments and patient records in one place.</p><form id="login-form"><div class="field"><label for="login-email">Email</label><input id="login-email" name="email" type="email" required autocomplete="username"></div><div class="field"><label for="login-password">Password</label><input id="login-password" name="password" type="password" required autocomplete="current-password" placeholder="Enter your password"></div><p class="form-error" id="login-error"></p><button class="primary-btn" type="submit">Sign in</button></form><div class="auth-switch">New here? <button type="button" data-action="show-signup">Create an account</button></div><small>Demo account: admin@caredesk.local / Admin@123</small></div>`;$('#login-email').focus()}
function showSignup(){document.body.classList.add('login-mode');$('#app').innerHTML=`<div class="login-card"><div class="login-logo">✚</div><p class="eyebrow">New practice workspace</p><h1>Create your account</h1><p>Your patients, doctors, and appointments will be private to your account.</p><form id="signup-form"><div class="field"><label for="signup-email">Email</label><input id="signup-email" name="email" type="email" required autocomplete="email"></div><div class="field"><label for="signup-password">Password</label><input id="signup-password" name="password" type="password" required minlength="8" autocomplete="new-password" placeholder="At least 8 characters"></div><div class="field"><label for="signup-confirm">Confirm password</label><input id="signup-confirm" name="confirmPassword" type="password" required minlength="8" autocomplete="new-password"></div><p class="form-error" id="signup-error"></p><button class="primary-btn" type="submit">Create account</button></form><div class="auth-switch">Already have an account? <button type="button" data-action="show-login">Sign in</button></div></div>`;$('#signup-email').focus()}
const patient = id => db.patients.find(item=>item.id===id);
const doctor = id => db.doctors.find(item=>item.id===id);
const byDateTime = (a,b) => `${a.date}T${a.time}`.localeCompare(`${b.date}T${b.time}`);
const button = (label, action, id, extra='') => `<button class="action-btn" data-action="${action}" data-id="${escapeHtml(id)}" ${extra}>${label}</button>`;
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3000)}
function header(title,subtitle,buttonLabel,action){return `<div class="page-head"><div><p class="eyebrow">Practice workspace</p><h1>${title}</h1><p>${subtitle}</p></div>${buttonLabel?`<button class="primary-btn" data-action="${action}">＋ ${buttonLabel}</button>`:''}</div>`}
function empty(title,description){return `<div class="empty"><span class="empty-icon">✳</span><strong>${title}</strong><span>${description}</span></div>`}
function stat(label,value,icon,foot){return `<article class="stat-card"><div class="stat-top"><span>${label}</span><span class="stat-icon">${icon}</span></div><div class="stat-value">${value}</div><div class="stat-foot">${foot}</div></article>`}
function badge(status){return `<span class="badge ${escapeHtml(status)}">${escapeHtml(status.replace('-',' '))}</span>`}
function avatar(name){return `<span class="avatar">${escapeHtml(initials(name))}</span>`}
function appointmentRows(items, compact=false){return items.map(a=>{const p=patient(a.patientId),d=doctor(a.doctorId);return `<tr><td><div class="name-cell">${avatar(p?.name||'?')}<span>${escapeHtml(p?.name||'Unknown patient')}</span></div></td><td>${escapeHtml(d?.name||'Unknown doctor')}<div class="muted">${escapeHtml(d?.specialty||'')}</div></td><td>${displayDate(a.date)}<div class="muted">${displayTime(a.time)} · ${a.duration} min</div></td><td>${badge(a.status)}</td>${compact?'':`<td><div class="actions">${button('View','view-appointment',a.id)}${button('Edit','edit-appointment',a.id)}</div></td>`}</tr>`}).join('')}
function appointmentTable(items,compact=false){return items.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Patient</th><th>Doctor</th><th>Date & time</th><th>Status</th>${compact?'':'<th>Actions</th>'}</tr></thead><tbody>${appointmentRows(items,compact)}</tbody></table></div>`:empty('No appointments found','Add an appointment or adjust your search.')}
function renderDashboard(){const today=localDate(),todayItems=db.appointments.filter(a=>a.date===today && a.status!=='cancelled').sort(byDateTime),upcoming=db.appointments.filter(a=>`${a.date}T${a.time}`>=`${today}T${new Date().toTimeString().slice(0,5)}` && a.status==='scheduled').sort(byDateTime);return `${header('Good day, welcome back','Here is what is happening at your practice today.','New appointment','add-appointment')}<div class="cards">${stat('Today’s appointments',todayItems.length,'▦','Scheduled for today')}${stat('Upcoming visits',upcoming.length,'◷','From this moment on')}${stat('Total patients',db.patients.length,'♙','Patients in your records')}${stat('Active doctors',db.doctors.length,'✚','Available in your directory')}</div><div class="grid-two"><section class="panel"><div class="panel-head"><h2>Today’s appointments</h2><button class="text-link" data-view="appointments">View all →</button></div>${appointmentTable(todayItems,true)}</section><section class="panel"><div class="panel-head"><h2>Today’s schedule</h2><span class="muted">${displayDate(today)}</span></div>${todayItems.length?`<div class="schedule-list">${todayItems.map(a=>`<div class="schedule-item"><span class="schedule-time">${displayTime(a.time)}</span>${avatar(patient(a.patientId)?.name||'?')}<div><strong>${escapeHtml(patient(a.patientId)?.name||'Unknown patient')}</strong><small>${escapeHtml(doctor(a.doctorId)?.name||'Unknown doctor')}</small></div>${badge(a.status)}</div>`).join('')}</div>`:empty('Clear schedule','No visits planned for today.')}<div class="note-box"><strong>Quick tip</strong><br>Choose a time slot when creating an appointment. CareDesk checks for overlapping bookings.</div></section></div>`}
function renderAppointments(){const q=query.toLowerCase();const items=db.appointments.filter(a=>{const text=`${patient(a.patientId)?.name||''} ${doctor(a.doctorId)?.name||''} ${a.reason}`.toLowerCase();return text.includes(q)&&(statusFilter==='all'||a.status===statusFilter)}).sort(byDateTime);return `${header('Appointments','Schedule visits and keep track of their progress.','New appointment','add-appointment')}<section class="panel"><div class="toolbar"><input class="search" id="search" type="search" placeholder="Search patient, doctor, or reason" value="${escapeHtml(query)}" aria-label="Search appointments"><select class="filter" id="status-filter" aria-label="Filter by status"><option value="all">All statuses</option>${['scheduled','completed','cancelled','no-show'].map(s=>`<option value="${s}" ${statusFilter===s?'selected':''}>${s.replace('-',' ')}</option>`).join('')}</select></div>${appointmentTable(items)}</section>`}
function renderPeople(type){const isPatient=type==='patients',items=db[type].filter(item=>`${item.name} ${item.email} ${item.phone} ${isPatient?'':item.specialty}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name));return `${header(isPatient?'Patients':'Doctors',isPatient?'Manage patient contact details and notes.':'Keep your care team directory up to date.',isPatient?'Add patient':'Add doctor',isPatient?'add-patient':'add-doctor')}<section class="panel"><div class="toolbar"><input class="search" id="search" type="search" placeholder="Search ${type}" value="${escapeHtml(query)}" aria-label="Search ${type}"></div>${items.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>${isPatient?'Date of birth':'Specialty'}</th><th>Email</th><th>Phone</th><th>Actions</th></tr></thead><tbody>${items.map(item=>`<tr><td><div class="name-cell">${avatar(item.name)}<span>${escapeHtml(item.name)}</span></div></td><td>${isPatient?displayDate(item.dob):escapeHtml(item.specialty)}</td><td>${escapeHtml(item.email||'—')}</td><td>${escapeHtml(item.phone||'—')}</td><td><div class="actions">${button('View',isPatient?'view-patient':'view-doctor',item.id)}${button('Edit',isPatient?'edit-patient':'edit-doctor',item.id)}</div></td></tr>`).join('')}</tbody></table></div>`:empty(`No ${type} found`,`Add a ${isPatient?'patient':'doctor'} or adjust your search.`)}</section>`}
function render(){const labels={dashboard:'Overview',appointments:'Appointments',patients:'Patients',doctors:'Doctors'};$('#breadcrumb-current').textContent=labels[view];$('.nav-item.active')?.classList.remove('active');$(`.nav-item[data-view="${view}"]`)?.classList.add('active');$('#app').innerHTML=({dashboard:renderDashboard,appointments:renderAppointments,patients:()=>renderPeople('patients'),doctors:()=>renderPeople('doctors')})[view]();$('#today-label').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'});}
function navigate(next){view=next;query='';statusFilter='all';$('.sidebar').classList.remove('open');render();}
function modal(title,body){$('#modal-root').innerHTML=`<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true" aria-label="${escapeHtml(title)}"><div class="modal-head"><h2>${escapeHtml(title)}</h2><button class="icon-button" data-action="close-modal" aria-label="Close">×</button></div><div class="modal-body">${body}</div></div></div>`;$('.modal input,.modal select,.modal button')?.focus()}
function closeModal(){$('#modal-root').innerHTML=''}
const field=(label,name,value='',type='text',required=false,extra='')=>`<div class="field ${extra}"><label for="field-${name}">${label}${required?' *':''}</label><input id="field-${name}" name="${name}" type="${type}" value="${escapeHtml(value)}" ${required?'required':''}></div>`;
const selectField=(label,name,items,value,placeholder)=>`<div class="field"><label for="field-${name}">${label} *</label><select id="field-${name}" name="${name}" required><option value="">${placeholder}</option>${items.map(item=>`<option value="${escapeHtml(item.id)}" ${value===item.id?'selected':''}>${escapeHtml(item.name)}${item.specialty?' · '+escapeHtml(item.specialty):''}</option>`).join('')}</select></div>`;
function formShell(fields,kind,id){return `<form id="record-form" data-kind="${kind}" data-id="${escapeHtml(id||'')}"><div class="form-grid">${fields}</div><p class="form-error" id="form-error"></p><div class="form-actions"><button type="button" class="secondary-btn" data-action="close-modal">Cancel</button><button class="primary-btn" type="submit">${id?'Save changes':'Create record'}</button></div></form>`}
function openPersonForm(type,id){const isPatient=type==='patient',record=(isPatient?db.patients:db.doctors).find(x=>x.id===id)||{};const fields=field('Full name','name',record.name,'text',true,'full')+field('Email','email',record.email,'email')+field('Phone','phone',record.phone,'tel')+(isPatient?field('Date of birth','dob',record.dob,'date'):`${field('Specialty','specialty',record.specialty,'text',true,'full')}`)+(isPatient?`<div class="field full"><label for="field-notes">Notes</label><textarea id="field-notes" name="notes">${escapeHtml(record.notes||'')}</textarea></div>`:'');modal(`${id?'Edit':'Add'} ${type}`,formShell(fields,type,id))}
function openAppointmentForm(id){if(!db.patients.length||!db.doctors.length){toast('Add a patient and a doctor before scheduling.');return}const a=db.appointments.find(x=>x.id===id)||{};const fields=selectField('Patient','patientId',db.patients,a.patientId,'Select patient')+selectField('Doctor','doctorId',db.doctors,a.doctorId,'Select doctor')+field('Date','date',a.date||localDate(),'date',true)+`<div class="field"><label for="field-time">Time *</label><input id="field-time" name="time" type="time" value="${escapeHtml(a.time||'09:00')}" required></div><div class="field"><label for="field-duration">Duration *</label><select id="field-duration" name="duration">${[15,30,45,60,90].map(n=>`<option value="${n}" ${Number(a.duration||30)===n?'selected':''}>${n} minutes</option>`).join('')}</select></div><div class="field"><label for="field-status">Status *</label><select id="field-status" name="status">${['scheduled','completed','cancelled','no-show'].map(s=>`<option value="${s}" ${a.status===s?'selected':''}>${s.replace('-',' ')}</option>`).join('')}</select></div>${field('Reason for visit','reason',a.reason,'text',false,'full')}`;modal(id?'Edit appointment':'New appointment',formShell(fields,'appointment',id))}
function showError(message){const el=$('#form-error');el.textContent=message;el.style.display='block'}
function minutes(time){const [h,m]=time.split(':').map(Number);return h*60+m}
function conflict(a){if(a.status==='cancelled')return '';const start=minutes(a.time),end=start+Number(a.duration);const other=db.appointments.find(b=>b.id!==a.id&&b.date===a.date&&b.status!=='cancelled'&&start<minutes(b.time)+Number(b.duration)&&end>minutes(b.time)&&(b.doctorId===a.doctorId||b.patientId===a.patientId));if(!other)return '';return other.doctorId===a.doctorId?'This doctor has another appointment during that time.':'This patient has another appointment during that time.'}
async function submitForm(form){const data=Object.fromEntries(new FormData(form));const kind=form.dataset.kind,id=form.dataset.id;let record;if(kind==='appointment'){record={patientId:data.patientId,doctorId:data.doctorId,date:data.date,time:data.time,duration:Number(data.duration),status:data.status,reason:data.reason.trim()};if(!record.patientId||!record.doctorId||!record.date||!record.time)return showError('Complete all required fields.')}else{record={name:data.name.trim(),email:data.email.trim(),phone:data.phone.trim(),...(kind==='patient'?{dob:data.dob,notes:data.notes.trim()}:{specialty:data.specialty.trim()})};if(!record.name||(kind==='doctor'&&!record.specialty))return showError('Complete all required fields.')}try{await request(`${kind}s${id?'/'+id:''}`,{method:id?'PUT':'POST',body:JSON.stringify(record)});closeModal();await refresh();toast(`${kind[0].toUpperCase()+kind.slice(1)} ${id?'updated':'added'}.`)}catch(error){showError(error.message)}}
function detailRow(label,value){return `<div class="summary-row"><span>${label}</span><strong>${escapeHtml(value||'—')}</strong></div>`}
function viewRecord(kind,id){if(kind==='appointment'){const a=db.appointments.find(x=>x.id===id);if(!a)return;modal('Appointment details',`${detailRow('Patient',patient(a.patientId)?.name)}${detailRow('Doctor',doctor(a.doctorId)?.name)}${detailRow('When',`${displayDate(a.date)} at ${displayTime(a.time)}`)}${detailRow('Duration',`${a.duration} minutes`)}${detailRow('Status',a.status.replace('-',' '))}${detailRow('Reason',a.reason)}<div class="form-actions"><button class="danger-btn" data-action="delete-appointment" data-id="${id}">Delete</button><button class="primary-btn" data-action="edit-appointment" data-id="${id}">Edit appointment</button></div>`);return}const isPatient=kind==='patient',item=(isPatient?db.patients:db.doctors).find(x=>x.id===id);if(!item)return;const appointments=db.appointments.filter(a=>isPatient?a.patientId===id:a.doctorId===id).length;modal(`${kind[0].toUpperCase()+kind.slice(1)} details`,`${detailRow('Name',item.name)}${detailRow('Email',item.email)}${detailRow('Phone',item.phone)}${detailRow(isPatient?'Date of birth':'Specialty',isPatient?displayDate(item.dob):item.specialty)}${isPatient?detailRow('Notes',item.notes):''}${detailRow('Appointments',String(appointments))}<div class="form-actions"><button class="danger-btn" data-action="delete-${kind}" data-id="${id}">Delete</button><button class="primary-btn" data-action="edit-${kind}" data-id="${id}">Edit ${kind}</button></div>`)}
function deleteRecord(kind,id){const list=kind==='appointment'?db.appointments:kind==='patient'?db.patients:db.doctors;const item=list.find(x=>x.id===id);if(!item)return;const linked=kind==='patient'?db.appointments.filter(a=>a.patientId===id).length:kind==='doctor'?db.appointments.filter(a=>a.doctorId===id).length:0;if(linked){toast(`Cannot delete: ${linked} appointment${linked===1?'':'s'} linked to this ${kind}.`);return}modal(`Delete ${kind}`,`<p class="confirm-copy">Delete ${escapeHtml(kind==='appointment'?'this appointment':item.name)}? This cannot be undone.</p><div class="form-actions"><button class="secondary-btn" data-action="close-modal">Cancel</button><button class="danger-btn" data-action="confirm-delete" data-kind="${kind}" data-id="${id}">Delete</button></div>`)}
document.addEventListener('click',async event=>{const target=event.target.closest('[data-action],[data-view]');if(!target){if(event.target.classList.contains('modal-backdrop'))closeModal();return}if(target.dataset.view){navigate(target.dataset.view);return}const action=target.dataset.action,id=target.dataset.id;if(action==='close-modal')closeModal();else if(action==='show-signup')showSignup();else if(action==='show-login')showLogin();else if(action==='logout'){try{await request('logout',{method:'POST'})}catch{}sessionStorage.removeItem(TOKEN_KEY);showLogin()}else if(action==='add-patient'||action==='edit-patient')openPersonForm('patient',id);else if(action==='add-doctor'||action==='edit-doctor')openPersonForm('doctor',id);else if(action==='add-appointment'||action==='edit-appointment')openAppointmentForm(id);else if(action.startsWith('view-'))viewRecord(action.slice(5),id);else if(action.startsWith('delete-'))deleteRecord(action.slice(7),id);else if(action==='confirm-delete'){const kind=target.dataset.kind;try{await request(`${kind}s/${id}`,{method:'DELETE'});closeModal();await refresh();toast(`${kind[0].toUpperCase()+kind.slice(1)} deleted.`)}catch(error){toast(error.message)}}});
document.addEventListener('submit',async event=>{if(event.target.id==='record-form'){event.preventDefault();await submitForm(event.target)}else if(event.target.id==='login-form'||event.target.id==='signup-form'){event.preventDefault();const signup=event.target.id==='signup-form',data=Object.fromEntries(new FormData(event.target));const errorEl=$(`#${signup?'signup':'login'}-error`);if(signup&&data.password!==data.confirmPassword){errorEl.textContent='Passwords do not match.';errorEl.style.display='block';return}try{const result=await request(signup?'signup':'login',{method:'POST',body:JSON.stringify({email:data.email,password:data.password})});sessionStorage.setItem(TOKEN_KEY,result.token);document.body.classList.remove('login-mode');await refresh()}catch(error){errorEl.textContent=error.message;errorEl.style.display='block'}}});
document.addEventListener('input',event=>{if(event.target.id==='search'){const position=event.target.selectionStart;query=event.target.value;render();const input=$('#search');input.focus();input.setSelectionRange(position,position)}});
document.addEventListener('change',event=>{if(event.target.id==='status-filter'){statusFilter=event.target.value;render()}});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal()});
$('#menu-toggle').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
if(sessionStorage.getItem(TOKEN_KEY)){refresh().catch(error=>toast(error.message))}else showLogin();
